### PR TITLE
Revert "Added hiding console window for you!"

### PR DESCRIPTION
**Pull request by Vedant-Bhalgama**
Reverts Vedant-Bhalgama/Dr0pFi#1

### CODE REVIEW

**Comment by 1d8** [comment]
You have to install pywin32 via 'pip install pywin32' in order for it to be compiled, let me know if you're still having problems!

**Comment by Vedant-Bhalgama** [comment]
I already have installed pywin32, Now what should i do next?

**Comment by 1d8** [comment]
After that the code should run just fine, what error are you running into?

**Comment by Vedant-Bhalgama** [comment]
see, I installed pywin32 first, then i ran build.py which compiles the code to executable, And when i run it, no console window comes but i dont get any mail also.

**Comment by 1d8** [comment]
That's really odd, I unfortunately don't have a gmail account or a proper Windows environment to test it in but I don't think the code should be interfering with the main functionality. Maybe try commenting out the consolehide() function call & seeing if the code errors out?

**Comment by Vedant-Bhalgama** [comment]
I will surely see to it, I think that pywin32 is breaking code

**Pull request closed without merging**
